### PR TITLE
clean up files; make var names pc

### PR DESCRIPTION
**Pull request by aaronkh**

### CODE REVIEW

**Comment by DevinMui** [comment]
thanks

**Comment by dcscooter** [comment]
Hey Aaron could we talk about the scooter App?! It’s so sick and I’m so overwhelmed trying to build
This app and can’t.

**Comment by DevinMui** [comment]
@dcscooter This is probably the wrong place to talk about that. Could you move the discussion into an issue on @aaronkh's repository? Thanks.

**Comment by dcscooter** [comment]
Yes so sorry didn’t mean to and am new
  

  
  

  
  
>

**Pull request merged**
